<?php
//RUSSELL
define("MERCHANT","547328202");
define("AccessKey","AKIAJ6IS2IDNGBREXEYA");
define("SecretAccessKey","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");

//DEV
// define("MERCHANT","110768107");
// define("AccessKey","AKIAJMS5RZP6ISU4T35Q");
// define("SecretAccessKey","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");

//PRD
//define("MERCHANT","341198082");
//define("AccessKey","AKIAJWSPNBYPUWU3CKMQ");
//define("SecretAccessKey","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");
?>
